### ISSUE TITLE
SFTP using a keyfile not working

### ISSUE THREAD

**Issue by mgoggie** [iterate-ch/cyberduck#12857] opened 2022-02-05 21:50 UTC
Getting Broken transport; encountered EOF. The connection attempt was rejected. The server may be down, or your network may not be properly configured.

Connection works using Filezilla.

Version 8.2.3 (36880)

**Comment by jonathandhn** [comment] 2022-05-08 17:07
I'm on the same predicament since yesterday ( Macos 12.3.1, Cyberduck  8.3.3 ), ssh keys on ~/.ssh path. None of the SFTP storage works anymore, what ever the server, selecting a key do nothing.

**Comment by ylangisc** [comment] 2022-06-28 12:57
Might be related or a duplicate of #13442.

**Closed** 2022-08-17 13:42 UTC
Labels: sftp
