### ISSUE TITLE
CyberDuck 8.4.3, 8.4.4 don't stop download at 100%

### ISSUE THREAD

**Issue by campbellpj** [iterate-ch/cyberduck#13736] opened 2022-09-16 17:05 UTC
Mac OS Catalina 10.15.7 

CyberDuck 8.4.3 and 8.4.4

Downloads of large files (22MB, 48 MB) keep going to 337%, keep asking for access key in keychain.

Downloads of small files also repeatedly ask for access key but then download OK.

**Comment by krilupo** [comment] 2022-10-03 11:21
might be a duplicate of #13374

**Closed** 2022-10-24 07:06 UTC
