### ISSUE TITLE
Takes long to open app.

### ISSUE THREAD

**Issue by alirz1** [iterate-ch/cyberduck#14085] opened 2023-01-15 01:17 UTC
The cyberduck app takes about 13-15 seconds to open, on a relatively new Intel i7 laptop with a nvme drive. What is it doing at launch to cause this delay?

**Comment by AliveDevil** [comment] 2023-01-18 10:06
Duplicate of #12630.
We are aware of possible startup delays. Depends on a lot of factors, which aren't easily resolved.

**Closed by AliveDevil** 2023-01-18 10:06 UTC
Labels: interface, enhancement
