### ISSUE TITLE
Folder download overwrites files without prompt

### ISSUE THREAD

**Issue by christianbrodbeck** [iterate-ch/cyberduck#12873] opened 2022-02-13 21:29 UTC
macOS App Store Version 8.2.3 (36880)

The settings suggest that an attempt to download a file that already exists should result in a prompt (screenshot).

However, when I drag a folder from Cyberduck to a local location and that folder already exists, Cyberduck overwrites all local files without asking first.

Please let me know if any additional information would be useful.

Could be related to https://github.com/iterate-ch/cyberduck/issues/12860

<img width="936" alt="image" src="https://user-images.githubusercontent.com/145771/153775693-ea952494-561c-449d-ae5f-59ccf5fa73db.png">

**Comment by AliveDevil** [comment] 2022-02-14 10:59
Closing here. It is indeed a duplicate of #12860.

For more information check [this comment](https://github.com/iterate-ch/cyberduck/issues/12860#issuecomment-1038942661)

**Closed by AliveDevil** 2022-02-14 10:59 UTC
