### ISSUE TITLE
Backblaze S3 Unsupported header 'x-amz-checksum-sha256' received for this API call

### ISSUE THREAD

**Issue by Dexus** [iterate-ch/cyberduck#16107] opened 2024-07-07 17:52 UTC
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
I have installed the latest 9.0.0 version, after I was not able anymore to upload any file to backblaze, I clicked on settings, then the App crashes everytime.

**To Reproduce**

**Expected behavior**
Working Cyberduck, where i can upload files and open the settings.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] Win
 - Version [e.g. 22] 11

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.
[cyberduck.log](https://github.com/user-attachments/files/16120203/cyberduck.log)

**Additional context**

**Comment by Dexus** [comment] 2024-07-07 18:19
btw. the file in the logs are 0 byte, i have also deletet them but did not change anything.

**Comment by dkocher** [comment] 2024-07-07 20:42
```

2024-07-07 19:35:18,645 [Thread-5] ERROR ch.cyberduck.core.TransferErrorCallbackControllerFactory - Failure loading callback class class cli.Ch.Cyberduck.Ui.Winforms.Threading.DialogTransferErrorCallback. cli.Ch.Cyberduck.Ui.Winforms.Threading.DialogTransferErrorCallback.<init>()
2024-07-07 19:35:18,654 [Thread-5] ERROR ch.cyberduck.core.AlertCallbackFactory - Failure loading callback class class cli.Ch.Cyberduck.Ui.Winforms.Threading.DialogAlertCallback. cli.Ch.Cyberduck.Ui.Winforms.Threading.DialogAlertCallback.<init>()
```

**Comment by AliveDevil** [comment] 2024-07-08 11:04
Missed changed constructor args for callbacks in https://github.com/iterate-ch/cyberduck/pull/15912:

Broken:
```
windows\src\main\csharp\ch\cyberduck\ui\winforms\threading\DialogAlertCallback.cs
windows\src\main\csharp\ch\cyberduck\ui\winforms\threading\DialogRecursiveCallback.cs
windows\src\main\csharp\ch\cyberduck\ui\winforms\threading\DialogTransferErrorCallback.cs
```

**Comment by AliveDevil** [comment] 2024-07-08 14:20
Moved the missing failure alerts to #16113.

Let's focus on the crash reports: Can you attach the crash report (latest file in `%AppData%\Cyberduck\CrashReporter`) using the GitHub web interface, or e-mail that to support@cyberduck.io with subject "GH-16107".

**Comment by Dexus** [comment] 2024-07-08 14:29
[638559776333228294.txt](https://github.com/user-attachments/files/16130576/638559776333228294.txt)
[638559776649681708.txt](https://github.com/user-attachments/files/16130577/638559776649681708.txt)
[638559776871134624.txt](https://github.com/user-attachments/files/16130578/638559776871134624.txt)
[638559777262528868.txt](https://github.com/user-attachments/files/16130579/638559777262528868.txt)
[638559777492993281.txt](https://github.com/user-attachments/files/16130581/638559777492993281.txt)
[638559784896420342.txt](https://github.com/user-attachments/files/16130582/638559784896420342.txt)
[638559792402909838.txt](https://github.com/user-attachments/files/16130583/638559792402909838.txt)
[638559793191837011.txt](https://github.com/user-attachments/files/16130584/638559793191837011.txt)

**Comment by AliveDevil** [comment] 2024-07-08 14:39
Please navigate to `%LocalAppData%\iterate GmbH` and move _all_ `Cyberduck.exe_Url`-folders to a temporary location.
Then navigate to `%AppData%\Cyberduck` and either move away the file `Cyberduck.user.config` or delete the line containing `connection.protocol.default` (as in https://github.com/iterate-ch/cyberduck/issues/15795#issuecomment-2045093050).

Can confirm, that with 9.0.0 having this line
``` xml
<setting name="connection.protocol.default" value="bad" />
```
in the `Cyberduck.user.config` crashes the application. Will need to amend that.

**Comment by Dexus** [comment] 2024-07-08 15:00
> Please navigate to `%LocalAppData%\iterate GmbH` and move _all_ `Cyberduck.exe_Url`-folders to a temporary location.

this path is not there - but `%AppData%\iterate_GmbH` with the folder prefix. - i created a zip and removed it.



> Then navigate to `%AppData%\Cyberduck` and either move away the file `Cyberduck.user.config` or delete the line containing `connection.protocol.default` (as in [#15795 (comment)](https://github.com/iterate-ch/cyberduck/issues/15795#issuecomment-2045093050)).

removed the line, now it works again without a crash.

However, there is now the problem that I make uploads that seem to be successful but never appear on backblaze. (at least not within 10 minutes)

**Comment by AliveDevil** [comment] 2024-07-08 15:12
> but %AppData%\iterate_GmbH with the folder prefix

Apologies, I really thought it was local appdata.

> However, there is now the problem that I make uploads that seem to be successful but never appear on backblaze. (at least not within 10 minutes)

This is an issue with the current 9.0.0-release. An alert window should be shown, but due to an issue this doesn't happen, so the upload is canceled, and marked as completed.

Please enable debug logging in the preferences window again, and retry the upload.
Attach the cyberduck log file either here (warning: public) or as e-mail attachment to support@cyberduck.io.
With the debug log, the real issue will be logged.

**Comment by Dexus** [comment] 2024-07-09 07:54
Hi, have send the log by mail.

**Comment by AliveDevil** [comment] 2024-07-09 08:00
{noformat}
> PUT /002.jpg HTTP/1.1
> Content-Type: image/jpeg
> x-amz-acl: private
> x-amz-checksum-sha256: Gy+ntJ0qfWk+w9o7XUbDRHFfm2is2lK7mooEHCuNl3E=
> x-amz-content-sha256: 1b2fa7b49d2a7d693ec3da3b5d46c344715f9b68acda52bb9a8a041c2b8d9771
> x-amz-storage-class: STANDARD
> Content-Length: 320545
> Host: ***.eu-central-003.backblazeb2.com
> Connection: Keep-Alive
> User-Agent: Cyberduck/9.0.0.41777 (Windows 10/10.0.22631.0) (amd64)
> Accept-Encoding: gzip,deflate
> Expect: 100-continue
> x-amz-date: 20240709T074721Z
> Authorization: ********
< HTTP/1.1 400 
< Server: nginx
< Date: Tue, 09 Jul 2024 07:47:23 GMT
< Content-Type: application/xml
< Content-Length: 200
< Connection: keep-alive
< x-amz->-: f15a449517f8b909
< x-amz-id-2: ade1uE2uxbjtvOXd2bpg=
< Cache-Control: max-age=0, no-cache, no-store
< Strict-Transport-Security: max-age=63072000
{noformat}

{noformat}
Caused by: org.apache.http.client.HttpResponseException: status code: 400, reason phrase: Unsupported header 'x-amz-checksum-sha256' received for this API call.
	at ch.cyberduck.core.s3.S3ExceptionMappingService.map(S3ExceptionMappingService.java:120) ~[Cyberduck.Protocols.DLL:10a5fb9d32e92c0422eccaf7936efce7d9cb4dd0]
	at ch.cyberduck.core.s3.S3ExceptionMappingService.map(S3ExceptionMappingService.java:43) ~[Cyberduck.Protocols.DLL:10a5fb9d32e92c0422eccaf7936efce7d9cb4dd0]
	at ch.cyberduck.core.AbstractExceptionMappingService.map(AbstractExceptionMappingService.java:53) ~[Cyberduck.Core.DLL:10a5fb9d32e92c0422eccaf7936efce7d9cb4dd0]
	at ch.cyberduck.core.s3.S3WriteFeature$1.call(S3WriteFeature.java:86) ~[Cyberduck.Protocols.DLL:10a5fb9d32e92c0422eccaf7936efce7d9cb4dd0]
	at ch.cyberduck.core.s3.S3WriteFeature$1.call(S3WriteFeature.java:73) ~[Cyberduck.Protocols.DLL:10a5fb9d32e92c0422eccaf7936efce7d9cb4dd0]
	at ch.cyberduck.core.http.AbstractHttpWriteFeature$2.run(AbstractHttpWriteFeature.java:99) ~[Cyberduck.Core.DLL:10a5fb9d32e92c0422eccaf7936efce7d9cb4dd0]
	at ch.cyberduck.core.threading.NamedThreadFactory$1.run(NamedThreadFactory.java:59) ~[Cyberduck.Core.DLL:10a5fb9d32e92c0422eccaf7936efce7d9cb4dd0]
	at java.lang.Thread.run(Thread.java:955) ~[?:1.8.0]
{noformat}

**Comment by AliveDevil** [comment] 2024-07-09 08:09
Backblaze isn't S3 API compatible: [S3-Compatible API#Unsupported Features](https://www.backblaze.com/docs/cloud-storage-s3-compatible-api#unsupported-features)

> Requests that include the following checksum HTTP headers are rejected with a `400 Bad Request` response:
> - x-amz-checksum-crc32
> - x-amz-checksum-crc32c
> - x-amz-checksum-sha1
> - x-amz-checksum-sha256
> - x-amz-checksum-algorithm
> - x-amz-checksum-mode

Backblaze doesn't care about their S3 API compatibility, please use the Backblaze protocol instead.

**Comment by AliveDevil** [comment] 2024-07-09 08:28
Closing as this should be resolved by either using the Backblaze S3-profile, or disabling `s3.upload.checksum.header`.
Was handled in #15841.

**Closed by AliveDevil** 2024-07-09 08:28 UTC
Labels: bug, s3, thirdparty, b2
