### ISSUE TITLE
More options for the default checkbox "save password" on the Cryptomator password prompts. Maybe a "never store password for this cryptomator folder" option.

### ISSUE THREAD

**Issue by mdotscott** [iterate-ch/cyberduck#14610] opened 2023-05-03 06:13 UTC
**Is your feature request related to a problem? Please describe.**
I am very happy with cyperduck, espacially due to the fact that it has the cryptomator implementation.

**Describe the solution you'd like**
I would be very happy to have an option that allows to say: "hey I do not want to have the password for my cryptomator folders stored ever", currently the "save password" checkbox in the cryptomator folders passwort prompt is checked by default and I cannot find any option in the settings to change this. Therefore I have to be really cautious to uncheck this checkbox before typing in my password and submitting it. I just feel safer to type the password every time, if I forget it someday it is my fault but I just do not want it to be stored accidentally.

**Describe alternatives you've considered**
Currently I am unchecking the checkbox for the "save password" option in the cryptomator password prompt each time.

**Additional context**
The checkbox "save password" for the cryptomator folder password prompt and related prompts.

**Comment by dkocher** [comment] 2023-05-03 06:16
Closing as duplicate of #11694 and #11647.

**Closed by dkocher** 2023-05-03 06:16 UTC
Labels: enhancement, cryptomator
