### ISSUE TITLE
Backblaze won't list items in folder

### ISSUE THREAD

**Issue by ChrisM61** [iterate-ch/cyberduck#14779] opened 2023-06-08 14:13 UTC
I am using a Mac running Ventura 13.1. I have a Backblaze B2 account. CyberDuck has been working well until I updated to version 8.60. Now I see the main folder but can't see a list of all the files in that folder. I can go back to 8.5 versions and it works. I have uninstalled CyberDuck 8.60 and reinstalled but it still doesn't work right.

Thanks,
Chris

**Comment by dkocher** [comment] 2023-06-08 14:39
Possible duplicate of #14768.

**Comment by Glitch3dPenguin** [comment] 2023-06-12 02:36
I also am having trouble with Cyberduck listing files in any B2 storage. I am using version 8.6.0 running Windows 11. Logs check out okay.

**Comment by dkocher** [comment] 2023-06-12 07:11
@ChrisM61  @Glitch3dPenguin Please reproduce the problem after checking _Preferences → Connection → Log → Enable debug log_ and attach the log output named `cyberduck.log` by choosing _Preferences → Connection → Log → Show_.

**Comment by sunnypsmith** [comment] 2023-06-13 16:01
Same problem. 
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/11736886/cyberduck.log)

**Closed** 2023-06-19 09:14 UTC
Labels: b2
