### ISSUE TITLE
Secure WebDav broken with update to 8.7.0

### ISSUE THREAD

**Issue by rockaceone** [iterate-ch/cyberduck#15223] opened 2023-10-19 16:12 UTC
When I updated to 8.7.0, I am only able to use system  keychain certificates to authenticate a secure WebDav server.  In previous versions and am able to use login keychain certificates, which is where my cert is stored to gain access.  Downgrading back to 8.6.3 until this is fixed

**Comment by dkocher** [comment] 2023-10-20 07:57
I cannot seem to reproduce the problem obtaining certificates with a private key from Keychain. Can you please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level) and attach the log file or send it to [support@cyberduck.io](mailto:support@cyberduck.io).

**Comment by rockaceone** [comment] 2023-10-20 11:53
I am currently downgraded to the previous version.  However, I am not sure the log file would help much.  It can't connect to WebDav because I can't select the certificate.  It shows like this when I upgrade:

<img width="529" alt="image" src="https://github.com/iterate-ch/cyberduck/assets/3729804/3ea045bd-2b75-4d6e-9b0e-9f162ebf6e6e">

But currently if I click that dropdown I have available certificates from the system and login keychains.  But when I upgrade, I only get the system ones and therefore can't select the one I need.  If you still need a log file, let me know and I'll upgrade and reproduce the problem.

**Comment by dkocher** [comment] 2023-10-20 13:05
>  If you still need a log file, let me know and I'll upgrade and reproduce the problem.
You might want to have a look at the current log file without upgrading again as it might already contain some error logging about retrieving keys from Keychain.

**Comment by kittonian** [comment] 2023-10-30 20:15
It's not just rockaceone. I am seeing the exact same issue on Mac OS Sonoma 14.1 after updating to 8.7.0 and filed a separate bug report (because I didn't see this one).

**Comment by dkocher** [comment] 2023-10-31 06:53
> It's not just rockaceone. I am seeing the exact same issue on Mac OS Sonoma 14.1 after updating to 8.7.0 and filed a separate bug report (because I didn't see this one).

In #15300.

**Comment by dkocher** [comment] 2023-10-31 07:04
Might be caused by 9d399bb8.

**Comment by dkocher** [comment] 2023-10-31 09:02
Might be resolved with updating the runtime in #15287.

**Comment by dkocher** [comment] 2023-10-31 09:06
Looks like this is caused by a change as discussed in [JDK-8303465](https://bugs.openjdk.org/browse/JDK-8303465). However this supposed to be resolved with [JDK-8309936](https://bugs.openjdk.org/browse/JDK-8309936) that was part of [17.0.8](https://bugs.openjdk.org/issues/?jql=project+%3D+JDK+AND+fixVersion+%3D+17.0.8).

**Comment by dkocher** [comment] 2023-10-31 09:07
> Looks like this is caused by a change as discussed in [JDK-8303465](https://bugs.openjdk.org/browse/JDK-8303465). However this supposed to be resolved with [JDK-8309936](https://bugs.openjdk.org/browse/JDK-8309936) that was part of [17.0.8](https://bugs.openjdk.org/issues/?jql=project+%3D+JDK+AND+fixVersion+%3D+17.0.8).

Also found [JDK-8309985](https://bugs.openjdk.org/browse/JDK-8309985) which claims a fix in [17.0.9](https://bugs.openjdk.org/issues/?jql=project+%3D+JDK+AND+fixVersion+%3D+17.0.9)

**Comment by dkocher** [comment] 2023-10-31 20:06
Can you let us know if you can reproduce with [snapshot](https://docs.cyberduck.io/cyberduck/faq/#snapshot-and-beta-builds) build 8.7.1.40738.

**Comment by dkocher** [comment] 2023-11-01 12:15
> Can you let us know if you can reproduce with [snapshot](https://docs.cyberduck.io/cyberduck/faq/#snapshot-and-beta-builds) build 8.7.1.40738.

@rockaceone @treyg @kittonian

**Closed** 2024-01-02 14:50 UTC
Labels: bug, webdav
