### ISSUE TITLE
Recursive file permission changes not applying recursively in Cyberduck 8.5.2 (38799) for Windows

### ISSUE THREAD

**Issue by elohanlon** [iterate-ch/cyberduck#14004] opened 2022-12-16 20:34 UTC
**Describe the bug**
In the latest Windows version of Cyberduck – version 8.5.2 (38799) – when I select a remote server directory and try to recursively change file permissions for that directory, only the top directory's permissions are changed.  None of the child files or subdirectories are modified.

By comparison, trying exactly the same operation in the latest Mac version – also Version 8.5.2 (38799) – works properly.  I tried this Mac test on the same remote server directory.

**To Reproduce**
1. Install a fresh copy of Cyberduck for Windows and keep all default settings.
2. Connect to a server over SFTP with username and password (or username and ssh key).
3. Create a directory on the server (let's call it "permission-test-dir") with some nested files and subdirectories, making sure that you're creating this directory in a place where you have the necessary permissions to create new files.
4. Right click on "permission-test-dir" and select "Info".
5. In the dialog that opens, select the "Permissions" tab.
6. Type in the new, desired permission value (I've done tests with 770, 771, 776, and other variations).
7. Click "Apply changes recursively".
8. Click "Continue" on the prompt that follows.  (I am only presented with this prompt once.)
9. Right click on "permission-test-dir" and select "Refresh" (to ensure that we're looking at the latest permission state).
10. Observe that "permission-test-dir" permissions have changed to the new value (good).
11. Observe that permissions for files and subdirectories inside "permission-test-dir" have NOT been recursively changed to the desired value (bad).

I also wanted to note here that in step 8, when trying the same test in the Mac version, I am prompted with more than one "Continue" prompt – one for the directory I am trying to modify, and an additional one for each of the subdirectories.

**Expected behavior**
In the "Steps to reproduce" above, I would have expected that in step 11, all child files and subdirectories inside "permission-test-dir" would have been updated to have the same permissions as "permission-test-dir".

**Desktop (please complete the following information):**
 - OS: Verified failure case on Windows 11 and Windows 10.
 - Cyberduck Version 8.5.2 (38799)

No problem in Cyberduck 8.5.2 (38799) on macOS 12.6.2.

**Log Files**
My Cyberduck log file was empty.

**Comment by AliveDevil** [comment] 2023-05-03 09:46
Thanks for reporting!

Found the root cause of this. Will be fixed in an upcoming release.

**Comment by AliveDevil** [comment] 2023-05-03 09:52
Regression in … 2016 😳
09e34dbfbb8eed708ebe0f528d232f1303c86a6d

**Closed** 2023-05-03 11:54 UTC
Labels: bug, interface

**Comment by elohanlon** [comment] 2023-05-03 17:45
@AliveDevil Thank you!
