### ISSUE TITLE
Unable to connect via SFTP with windows client

### ISSUE THREAD

**Issue by davidrot** [iterate-ch/cyberduck#12726] opened 2021-12-29 15:33 UTC
Hello,
I am unable to connect to my vps via ssh key (ed or rsa). It is working for me with the same credentials on mac (7.4.1).  I have tried several versions for windows 8.2.0, 8.0.0 and 7.10.0. I have tried two different remote machines. 

I have checked the auth.log, first 4 lines are from windows, last line is from mac.

```
Dec 29 16:25:32 vmd85532 sshd[]: Received disconnect from 185.17.205.xx port 16509:11:  [preauth]
Dec 29 16:25:32 vmd85532 sshd[]: Disconnected from authenticating user root 185.17.205.xx port 16509 [preauth]
Dec 29 16:25:47 vmd85532 sshd[]: Received disconnect from 185.17.205.xx port 16491:11:  [preauth]
Dec 29 16:25:47 vmd85532 sshd[]: Disconnected from authenticating user root 185.17.205.xx port 16491 [preauth]
Dec 29 16:27:40 vmd85532 sshd[]: Accepted publickey for root from 185.17.205.xx port 16434 ssh2: ED25519 SHA256:+GWJXWOEDTdb99xrBBPe8IYkM2wZkEK6ZGT7MPN+1sg
```

**Comment by dkocher** [comment] 2022-01-05 22:50
Possible duplicate of #12733.

**Comment by ylangisc** [comment] 2022-01-06 07:54
Can you please post the debug output when executing the following command on your macOS?
```
ssh -i [KEYFILE] [HOSTNAME] -vv
```

**Closed** 2022-06-28 13:33 UTC
Labels: help wanted, sftp
