### ISSUE TITLE
Under Windows 11 it does not remember last opened folder

### ISSUE THREAD

**Issue by Sun3** [iterate-ch/cyberduck#12821] opened 2022-01-25 19:04 UTC
Before I upgraded from Windows 10 to Windows 11 when I re-opened Cyberduck it would open to the last FTP folder that was open. Once upgraded to Windows 11, it does not remember and only opens up to the connect to server in the list.

Any workarounds?

Thank you.

**Comment by AliveDevil** [comment] 2022-01-26 09:51
Can you let me know which version of Cyberduck you are using (Microsoft Store, or standalone from website)?
Additionally: There is Preferences -> General "Save Workspace" option which is what you are looking for. Do you remember disabling that?

**Comment by Sun3** [comment] 2022-01-26 17:38
I am using version 8.2.1 (36773) and it is standalone from website. Yes, under Preferences -> General "Save Workspace" option is turned on.

**Comment by AliveDevil** [comment] 2022-03-03 11:57
Thanks for reporting. I can reproduce it here.

**Comment by AliveDevil** [comment] 2022-03-03 12:00
Stop using undocumented functions from VirtualDesktopManager. Instead rely on Windows behavior and best-practice, which might interfere with how users "want Windows virtual desktops to work". This is then intended behavior.

Won't happen before #12804 is merged.

**Closed** 2022-03-16 12:12 UTC
Labels: interface
