### ISSUE TITLE
Cannot read container configuration

### ISSUE THREAD

**Issue by eithel01** [iterate-ch/cyberduck#13528] opened 2022-06-30 00:21 UTC
Trying to open a bucket I get this error.  This bug is not present in previous version 8.3.0, I had to downgrade the version to resolve this issue.  Please take note.
My bucket properties hasn't been changed in years; so I gues this is a cyberduck problem.  Thank you. 

![Captura de pantalla 2022-06-29 181618](https://user-images.githubusercontent.com/30914622/176566716-81baa381-7fa3-4d26-9be2-f8be9670c4d4.jpg)

**Comment by BGR360** [comment] 2022-07-14 22:32
Latest version of Cyberduck has the same problem on MacOS. Downgrading to 8.3.0 also worked for me.

**Comment by bounlu** [comment] 2022-07-26 03:00
I had the same problem. Downgrading to 8.3.3 worked.

**Comment by derkzomer** [comment] 2022-08-09 06:21
Similar issue for me.

**Comment by dkocher** [comment] 2022-08-17 13:35
Possibly fixed with #13664.

**Comment by derkzomer** [comment] 2022-08-22 01:28
Unfortunately it still appears this is an issue with version 8.4.3.
![image](https://user-images.githubusercontent.com/5495981/185821593-9af11acc-6d69-450a-97c5-386920063e72.png)

**Comment by bounlu** [comment] 2022-08-22 02:18
> Unfortunately it still appears this is an issue with version 8.4.3. ![image](https://user-images.githubusercontent.com/5495981/185821593-9af11acc-6d69-450a-97c5-386920063e72.png)

so sad to hear, I was hoping to be able to upgrade for this version.

**Comment by dkocher** [comment] 2022-08-22 12:42
> Unfortunately it still appears this is an issue with version 8.4.3.

Please attach the [debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level) and send us the log file after reproducing the problem. If you don't like to see sensitive data shared publicly, please send the log file with the ticket reference GH-13528 support@cyberduck.io. Otherwise, attach it here.

**Sidenote**: If you want to share the log file here, make sure to attach it through the GitHub web interface, as it wouldn't be visible to us otherwise.

**Comment by bounlu** [comment] 2022-09-05 01:20
<img width="282" alt="Cyberduck" src="https://user-images.githubusercontent.com/17899927/188342488-035cc9ab-560c-4a53-ab81-9ec09c2ded3d.png">

**Comment by dkocher** [comment] 2022-09-05 06:48
> <img alt="Cyberduck" width="282" src="https://user-images.githubusercontent.com/17899927/188342488-035cc9ab-560c-4a53-ab81-9ec09c2ded3d.png">

Please attach the [debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level) and send us the log file after reproducing the problem.

**Comment by dkocher** [comment] 2022-09-09 06:46
> Unfortunately it still appears this is an issue with version 8.4.3.

Please attach the [debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level) and send us the log file after reproducing the problem.

**Comment by bounlu** [comment] 2022-09-19 13:49
I confirm this issue persists in version 8.4.4.

**Comment by bounlu** [comment] 2022-09-29 06:59
I confirm this issue persists in version 8.4.5.

**Comment by dkocher** [comment] 2022-09-29 08:30
> I confirm this issue persists in version 8.4.5.

Please attach the [debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level) and send us the log file after reproducing the problem.

**Comment by bounlu** [comment] 2022-10-06 06:33
I cannot attach debug logging due to security concerns but I can confirm the issue persists as of today.

**Comment by borsenkOoleh** [comment] 2022-10-25 11:25
Hey, guys!

I guess you are having the same issue as me before, try to connect to your S3 bucket in this way:
![Screenshot 2022-10-25 at 14 16 57](https://user-images.githubusercontent.com/102299131/197759455-f0318527-1971-4c31-b6e2-8ccd2b229925.png)

Some time ago Amazon changed endpoints for buckets, so you don't always need to specify AZ as it was before (e.g https://your-bucket-name.s3.eu-central-1.amazonaws.com) to connect to S3 through CyberDuck now (tested on a new version) you need to connect this way **https://s3.amazonaws.com/your-bucket-name**

**Comment by bounlu** [comment] 2022-10-25 11:30
I am already using it this way but it does not work for Cyberduck versions never than 8.3.3. I get the above error whenever I try to list a bucket.

**Comment by dkocher** [comment] 2022-10-28 11:53
> If you don't like to see sensitive data shared publicly, please send the log file with the ticket reference [GH-13528](https://github.com/iterate-ch/cyberduck/issues/13528) [support@cyberduck.io](mailto:support@cyberduck.io).

If you don't like to see sensitive data shared publicly, please send the log file with the ticket reference https://github.com/iterate-ch/cyberduck/issues/13528 [support@cyberduck.io](mailto:support@cyberduck.io).

**Comment by golottie-wasif** [comment] 2022-11-21 13:49
We had the same problem, re-adding the profile fixed it on v8.5

**Comment by bounlu** [comment] 2022-11-21 14:29
@golottie-wasif  Yes, it also worked for me! Thank you so much.

**Closed** 2022-12-13 09:35 UTC
Labels: help wanted, s3

**Comment by dkocher** [comment] 2023-01-11 09:49
Additional fix in #14062.

**Comment by wedelski** [comment] 2023-05-30 03:54
Having a similar issue in 8.5 macOS Big Sur

Can see all 6 of my buckets in Cyber, but can only interact with one of them. All the other 5 give me the error "Cannot read container configuration. Us-west-1." 

I've followed the instructions as above but only getting 1 of my 6 buckets.

**Comment by dkocher** [comment] 2023-05-30 06:57
> Can see all 6 of my buckets in Cyber, but can only interact with one of them. All the other 5 give me the error "Cannot read container configuration. Us-west-1."

Please open a new issue with the [debug log](https://docs.cyberduck.io/cyberduck/support/#logging-output) included.
