### ISSUE TITLE
UI doesn't support high resolution screens, it all looks blurry(include fonts and icons, etc)

### ISSUE THREAD

**Issue by andymaxo** [iterate-ch/cyberduck#16345] opened 2024-09-17 23:50 UTC
UI doesn't support high resolution screens, it all looks blurry(include fonts and icons, etc)

**Comment by AliveDevil** [comment] 2024-09-18 07:23
Duplicate of https://github.com/iterate-ch/cyberduck/issues/8961#issuecomment-1822247582

**Closed by AliveDevil** 2024-09-18 07:23 UTC
Labels: duplicate, interface, enhancement
