### ISSUE TITLE
Prompt to apply changes recursively when changing storage class for folder not always showing

### ISSUE THREAD

**Issue by unit1g** [iterate-ch/cyberduck#16254] opened 2024-08-25 17:49 UTC
**Describe the bug**
In Windows 10, when trying to change the storage class of a folder in Scaleway S3 bucket the pop-up window that asks if I want to apply this change to all files inside the folder won't show up, I get the sound cue, but no window, out of 10 attempts to change the storage class, a window pops up about 6 times.

**To Reproduce**
1. In Scaleway bucket.
2. Right-click a folder and select info.
3. Go to the S3 tab.
4. Select storage class and change from Standard to Glacier.
5. Pop-up cue sound, but no Pop-up shows up.

**Expected behavior**
A pop-up shows up asking which files should be applied to the new storage class

**Screenshots**
![image](https://github.com/user-attachments/assets/a2fcbe9a-8ddf-41d5-95f9-d820200e613b)

**Desktop
 - Windows 10 IoT Enterprise LTSC 
 - 21H2
 
 Cyberduck version 9.0.1

**Comment by dkocher** [comment] 2024-11-07 12:41
Possibly this [^1] check might cause the undetermenistic behaviour.

[^1]: https://github.com/iterate-ch/cyberduck/blob/5e1d091f8dab5a5e57f3ece02dff4205ee4bae3d/windows/src/main/csharp/ch/cyberduck/ui/winforms/threading/DialogRecursiveCallback.cs#L46

**Comment by dkocher** [comment] 2024-11-07 13:01
Possible duplicate of #6550.

**Closed** 2024-11-20 14:56 UTC
Labels: s3
