### ISSUE TITLE
The open connection popup is too small and all scrunched together on both monitors

### ISSUE THREAD

**Issue by chanback01** [iterate-ch/cyberduck#12748] opened 2022-01-05 18:43 UTC
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**

When I open the initial menu - the menu items are small.

When I open the OPEN CONNECTION popup - it is so small and scrunched, I cannot work with it.

**To Reproduce**
Open program
Click File
Click Open Connection
**Expected behavior**
I would expect to be able to see the pop up box clearly so I could enter the info

**Screenshots**
![cyber-duck-2-open-connection-pop-up](https://user-images.githubusercontent.com/97189383/148271257-229539b0-be85-47c6-9b18-d2decfa0fc13.jpg)

![cyber-duck-1-intial-screen](https://user-images.githubusercontent.com/97189383/148271226-3713ff3e-7fd1-43c5-ab5b-ca103c40be3c.jpg)

**Desktop (please complete the following

 information):**
 - OS: [e.g. macOS]

I am using windows 11
I uninstalled and reinstalled.

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.
I cannot find that, but I have not made any connection.  I cannot resize the Preferences window either.

**Additional context**
I hope you can help!

**Comment by AliveDevil** [comment] 2022-01-06 09:28
Duplicate of #12742.

**Closed by AliveDevil** 2022-01-06 09:28 UTC
