### ISSUE TITLE
issue uploading large files to S3 with v8.3.3 and 8.3.2

### ISSUE THREAD

**Issue by sunpath74** [iterate-ch/cyberduck#13339] opened 2022-04-29 06:44 UTC
When using Cyberduck versions 8.3.2 and 8.3.3, to upload large files to an S3 bucket - for example 15 GB, we get the error "Status code: 400, reason phrase: Your proposed upload exceeds the maximum allowed size."

Some members of the team still have Cyberduck 7.9.2 and are able to successfully upload.
We tried to upload files at least 15 GB that we had successfully posted in late March and early April to the same S3 bucket before some upgraded Cyberduck and the same user could not successfully upload the files.  We can also upload the same files using another program, for example Transmit, but only an older version of Transmit - 5.2.4. Tester mac OS is 10.13.6 which is too low for latest version of Transmit, but other users with latest version also are not able to upload large files to same S3.

We've looked at our S3 settings and are trying the S3 "Transfer Acceleration" feature as we initially thought this was because uploaders were in various global locations and the bucket is based in US.  Note that the Transfer Acceleration feature doesn't seem to have helped- file transfer still takes similar time and upload fails with Cyberduck 8.3.3 with same error. 

Any help from the Cyberduck side? We are working with kids' content providers who have large video files to transmit, and they were able to do so previously.

**Comment by sunpath74** [comment] 2022-04-29 15:31
I added some updated info above in the original comment after further testing this morning. 
Transfer acceleration does not seem to help. 
The actual latest version of Transmit also gives the same error, only older versions of Transmit that team member had still installed, are able to upload successfully the large file.

**Comment by sunpath74** [comment] 2022-04-29 16:42
Just to update this - we think we might have solved this with the below but testing a couple additional users to be sure.  

After turning on the Transfer Acceleration feature in S3, we added the below additional permissions to the IAM user that we were using to upload to S3. 
One allows Cyberduck to determine if the bucket has Transfer Acceleration enabled.
The other allows Cyberduck to manage multi-part uploads, which should allow Cyberduck to resume an upload if it gets interrupted.
s3:GetAccelerateConfiguration
s3:ListBucketMultipartUploads

I'm not sure why we didn't need these permissions set for the older version of Cyberduck version 7.9.2. But this seems to be better now with the permissions set.

**Comment by sunpath74** [comment] 2022-05-10 14:01
@dkocher thanks I am asking internally here about the IAM policy.  We have in the meantime had success with external partners using Cyberduck 7.9.2 to upload large files.  They are using the user with the additional parameters set but the old version of Cyberduck also worked before we changed the user parameters.

**Comment by sunpath74** [comment] 2022-05-10 18:46
@dkocher here's the original IAM policy we were using 
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::tv.hopster.assets.upload"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::tv.hopster.assets.upload/*",
                "arn:aws:s3:::videos-ready-for-ingest/*"
            ]
        }
    ]
}

**Comment by sunpath74** [comment] 2022-05-10 19:20
and this is the current policy with the permissions added:

This is the current IAM policy:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation",
                **"s3:GetAccelerateConfiguration",
                "s3:ListBucketMultipartUploads"**
            ],
            "Resource": [
                "arn:aws:s3:::tv.hopster.assets.upload",
                "arn:aws:s3:::tv-hopster-assets-upload-2"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::tv.hopster.assets.upload/*",
                "arn:aws:s3:::videos-ready-for-ingest/*",
                "arn:aws:s3:::tv-hopster-assets-upload-2/*"
            ]
        }
    ]
}
The new permissions are added and the new bucket is added. The same policy is used for uploading to both the old and the new bucket.

**Comment by mp-markg** [comment] 2022-05-13 18:04
I am having a similar issue. Interestingly, I was able to upload 17.5GB file from CyberDuck on Windows, but cannot get it to work from my Mac. Below is the IAM policy of the user:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutAnalyticsConfiguration",
                "s3:GetObjectVersionTagging",
                "s3:ReplicateObject",
                "s3:GetObjectAcl",
                "s3:PutLifecycleConfiguration",
                "s3:GetObjectVersionAcl",
                "s3:PutObjectTagging",
                "s3:DeleteObject",
                "s3:GetIpConfiguration",
                "s3:DeleteObjectTagging",
                "s3:GetBucketWebsite",
                "s3:PutReplicationConfiguration",
                "s3:DeleteObjectVersionTagging",
                "s3:GetBucketNotification",
                "s3:GetReplicationConfiguration",
                "s3:ListMultipartUploadParts",
                "s3:GetObject",
                "s3:PutBucketNotification",
                "s3:PutObject",
                "s3:PutBucketLogging",
                "s3:GetAnalyticsConfiguration",
                "s3:GetObjectVersionForReplication",
                "s3:GetLifecycleConfiguration",
                "s3:ListBucketByTags",
                "s3:GetBucketTagging",
                "s3:GetInventoryConfiguration",
                "s3:DeleteObjectVersion",
                "s3:GetBucketLogging",
                "s3:ListBucketVersions",
                "s3:ReplicateTags",
                "s3:RestoreObject",
                "s3:GetAccelerateConfiguration",
                "s3:ListBucket",
                "s3:GetBucketPolicy",
                "s3:GetEncryptionConfiguration",
                "s3:GetObjectVersionTorrent",
                "s3:AbortMultipartUpload",
                "s3:GetBucketRequestPayment",
                "s3:GetObjectTagging",
                "s3:GetMetricsConfiguration",
                "s3:ListBucketMultipartUploads",
                "s3:PutMetricsConfiguration",
                "s3:PutObjectVersionTagging",
                "s3:GetBucketVersioning",
                "s3:GetBucketAcl",
                "s3:PutInventoryConfiguration",
                "s3:GetObjectTorrent",
                "s3:GetBucketCORS",
                "s3:GetBucketLocation",
                "s3:GetObjectVersion",
                "s3:ReplicateDelete"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}",
                "arn:aws:s3:::${aws:username}/*"
            ]
        }
    ]
}
```

**Comment by dkocher** [comment] 2022-05-23 18:42
[Failures](https://github.com/iterate-ch/cyberduck/blob/ff2068f4d57d3cbfb89e43cadc74e50f8c32ca40/s3/src/main/java/ch/cyberduck/core/s3/S3MultipartUploadService.java#L112) listing previous multipart uploads because of a missing `s3:ListBucketMultipartUploads` in the policy should not causes issues as this is ignored when failing wit either `400` or `403`.

**Comment by dkocher** [comment] 2022-05-23 18:49
Improved error reporting in #13411.

**Comment by dkocher** [comment] 2022-05-23 18:55
Possible duplicate of #13386. Try to either
 * Edit the ownership control of the bucket to allow setting ACLs 
 or
 * Set _None_ in Preferences → S3 → Default ACL

This might also work by updating to the current snapshot build which has #13402 merged.

**Closed** 2022-06-16 07:09 UTC
Labels: help wanted, s3
