### ISSUE TITLE
Windows 11 "Download To" Shows only Desktop Folder

### ISSUE THREAD

**Issue by NogrTL** [iterate-ch/cyberduck#14211] opened 2023-02-09 09:31 UTC
### Steps:
1. Open CyberDuck
2. Open WebDAV server
3. Select File and click "Download To"

### Expected:
To see menu when you can select any folder available in Windows 11

### Actual:
Open window with only Desktop
![image](https://user-images.githubusercontent.com/12021449/217772593-3f8cad1a-4389-4517-ac9e-1429883145d9.png)

**Comment by Cassie205** [comment] 2023-02-22 13:52
I can't reproduce the issue using the latest snapshot build of Cyberduck (8.5.7.39400). Please update your application to see if the issue still persists.

**Comment by Cassie205** [comment] 2023-02-22 14:12
You can change the update feed in the Cyberduck preferences _Update_ tab to _Snapshot Builds_ to receive the latest bug fixes.

**Comment by NogrTL** [comment] 2023-02-22 14:17
Build 8.5.7.39400
Bug still persists.

**Comment by AliveDevil** [comment] 2023-02-23 11:26
We'll check what happens here - but this is an issue within Windows (which we may or may not be able to work around).

I checked and found this[^1] recent thread.
[^1]: https://www.datacad.com/bbs/viewtopic.php?f=73&t=17881

There this[^2] Microsoft question was mentioned, with this resolution:
[^2]: https://answers.microsoft.com/en-us/windows/forum/all/windows-11-browse-for-folder-dialog-issue-only/0a0ce0a5-0a72-4483-a51e-1b3ee9dffcdb
> Thanks. OneDrive seems to be the culprit. The workaround is to stop syncing your Desktop folder with OneDrive.
> Important: Before proceeding, copy the files in those special folders to another folder or external drive. Please don’t copy them anywhere under Desktop/Documents/Pictures. This is because disabling OneDrive backup for a folder erases the local copies of the files. Copying them to a different location beforehand will ensure that you don’t need to download them again from the OneDrive cloud.
> - Right-click the OneDrive icon in the Notification area and click Settings.
> - Select the Backup tab, and click Manage Backup
> - In the Manage folder backup dialog, click on the Stop backup link for "Desktop"
> - Click Stop backup in the confirmation dialog that appears.

(shout out to Ramesh Srinivasan)

**Comment by AliveDevil** [comment] 2023-02-23 11:57
Is this a good-enough workaround for you?

![image](https://user-images.githubusercontent.com/734738/220899177-28bd2340-27e2-4833-a715-a8b305f657e4.png)

**Comment by NogrTL** [comment] 2023-02-23 13:31
Thanks! That did work.

I would suggest changing that API for something - anyway. That's not a best UX for folder picking anyway.

**Comment by AliveDevil** [comment] 2023-02-24 10:03
Tracking in #14281, can't estimate, when this will be integrated though.

**Closed** 2023-02-24 10:04 UTC
Labels: bug, interface, enhancement, thirdparty
