### ISSUE TITLE
Bug Displaying “Transfer Incomplete”

### ISSUE THREAD

**Issue by bittyadvance-git-users** [iterate-ch/cyberduck#12838] opened 2022-01-31 21:15 UTC
**Describe the bug**
Kind of a weird bug… after what looks like a successful transfer of files from a Windows EC2 instance to an S3 bucket, there is an awkward delay/pause and then “**Transfer Incomplete**” appears.   However, the accurate file sizes are displayed in the destination.  I say file sizes because integrity hashes or checksums were not yet used to verify each file.

Please observe the two attached images.   Note that the initial number “xx GiB of xx GiB” is correct and always larger than the second number.

The files involved are production files so it was necessary to obscure those details. 

**To Reproduce**
Select 4 files from today, in Windows Explorer
Drag the files to the destination folder in CyberDuck

IMPORTANT:  This problem cannot be consistently reproduced every time, but it happens so often that we are at the point of considering GUI alternatives to CyberDuck.  But all of our dev’s are “married” to CyberDuck.  ( We want to avoid using the AWS CLI for file transfers. )

**Expected behavior**
The files are successfully copied to the folder in an S3 bucket and that correct status is displayed.

**Screenshots**
![IMG_1541](https://user-images.githubusercontent.com/90116634/151873933-a07d7528-3962-4387-92c9-8bfd0b0d08c3.png)

**Desktop (please complete the following information):**
 Windows server within Lightsail

**Log Files**
Not permitted to share these.   Sorry.

**Comment by and-rew** [comment] 2022-03-21 11:54
Confirming the same behaviour on MacOS version Version 8.2.3 (36880)
Uploading to encrypted folder to mail.ru cloud via WebDav. 5 big files (1.5 - 15 Gb).
Result: transfer incomplete, although the uploaded files sizes match and there are no errors in logs, except the notification itself:

`2022-03-21 01:32:28,624 [main] WARN  ch.cyberduck.core.notification.NotificationCenter - Discarded notification <NSUserNotification:0x7fd4f457f8c0> { title: "Transfer incomplete" informativeText: "20GB QUANTUM.zip.001… (6)" actionButtonTitle: "(null)" actualDeliveryDate: 2022-03-20 22:32:28 +0000 presented: NO identifier: 4c57b384-4d6c-452a-88b7-a189b07d59ff } without presenting`

![Screenshot 2022-03-21 at 14 03 10](https://user-images.githubusercontent.com/7512348/159253553-5c0acc65-12ff-4c38-a248-4777b3025ff9.png)

The problem is that with this kind of messages, as a user I'm not sure in these uploads, so I will have to download and extract to ensure integrity.

Regarding the incorrect progress bar there was another issue registered, but it was marked as fixed. Probably should be reopened.
https://github.com/iterate-ch/cyberduck/issues/5948

**Comment by conorahern8** [comment] 2022-09-23 18:00
Seeing the same issue uploading files to SFTP server on Cyberduck 8.4.3 on macOS. Dragged a bunch of files over to a folder, which should have totaled 868MB, but for some reason Cyberduck counted the total size as 783.9MB. So, the transfer kept going past the 100% of 783.9MB, uploaded all 868.4MB, then ended with an error message of "transfer incomplete", since I'm assuming Cyberduck is checking that the uploaded bytes == the source bytes size, which is not true in this condition.

<img width="518" alt="image" src="https://user-images.githubusercontent.com/35696968/192028893-f6588a01-6e19-4ee9-8e95-257cd167e2e9.png">

**Closed** 2023-06-27 20:12 UTC
Labels: sftp, s3, webdav
