### ISSUE TITLE
Moving bookmark using drag and drop will delete the bookmark

### ISSUE THREAD

**Issue by oklimberg** [iterate-ch/cyberduck#12897] opened 2022-02-17 12:23 UTC
When trying to re-arrange a newly created bookmark via drag and drop, the bookmark gets deleted if moving it more than a few rows upwards.
I currently got a list of 29 bookmarks. I duplicate on of the bookmarks at the top and the new one gets placed at the end of the list.
When I now try to move the new bookmark to the top, it gets deleted. The bug is not 100% persistent because different things can happen. Either the bookmark gets placed back at the end, it will be placed at the desired position or it will be deleted

1. Open list of bookmarks
2. if the list is not yet scrollable, duplicate existing entries or simply create new ones
3. duplicate/create a new bookmark once you have 30 bookmarks
4. move the newly created bookmark one position upwards
5. repeat number 4 until the bookmark which should be moved got deleted (check total number of bookmarks bottom left)

**Expected behavior**
No bookmarks get deleted be just moving them

**Desktop (please complete the following information):**
 - OS: macOS 11.6.4
 - Cyberduck:  8.2.3 (36880)

[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/8088552/cyberduck.log)

**Comment by tatze96** [comment] 2022-03-03 12:40
I can reproduce the described behavior. Cyberduck will either don't move the bookmark at all, move it to another place than expected, or in rare cases delete the bookmark instead of moving it.

**Comment by ferben** [comment] 2023-12-07 15:20
Unfortunately I have the same experience with this issue on macOS 14.1.2 + Cyberduck 8.7.1 (but appear on macOS 13 and 12 too). My bookmark list has 44 items.
Many times when I trying change bookmarks order, bookmark jump at the end of list unexpectedly, even when Drop area is highlighted (blue line) ⇒ this should be improved.
But sometimes bookmark does not jump at the list end, but completely disappear and I have to make the bookmark again.

**Comment by porg** [comment] 2024-10-29 16:49
## Data loss is most often a severe bug IMHO
- @dkocher I experienced this myself today
- macOS: 13.7 Ventura
- Cyberduck:  9.0.2 (42108)
- Mountain Duck: 4.16.3 (only installed today)

## My experience of that bug
- In Mountain Duck I had attempted to create a SMB bookmark, but did not find it.
  - I think I aborted.
  - But by that time Mountain Duck very likely has had accessed the bookmark storage in read/write mode.
- In Cyberduck I later created a new bookmark.
  - Then wanted to reorder that bookmark and my other bookmarks too.
  - Instead of being re-ordered after some drag'n'drop operations the repective bookmark was gone.
  - In some instances it resurfaced (at another position).
  - Also quitting and re-opening Cyberduck did not help.
  - They were gone not only in presentation, but seem to have been really removed from where they were persisted.
- From 11 bookmarks I'm now down to 8 and in fear of loosing further ones I do not dare to drag them around.

## Observations
- Note that today I had installed MountainDuck in trial/evaluation mode for the first time, which accesses the bookmarks from CyberDuck too. Maybe that is causally related? Or just a coincidence.
 - I am not sure whether I ever used the re-order function in Cyberduck before, but it is likely. And I cannot recall data loss from this ever.
- So it is somehow plausible that this is somehow connected to Cyberduck and MountainDuck accessing the same bookmarks.

**Comment by porg** [comment] 2024-10-29 18:33
@dkocher I digged a little deeper and I think I found the root cause of that bug:
@ferben , @tatze96, @oklimberg : Did any of you have Mountain Duck in use too when experiencing the bug in Cyberduck?

## Cyberduck and Mountain Duck use the same centralized bookmarks but each app has slightly different sorting options, which seemingly can result in a destructive conflict:

**Mountain Duck** allows to sort by: Nickname or Hostname or Protocol
- by going to: Main Menu → Menu items on the right hand side → Mountain Duck menu item → Sort By → Choose 1 of 3 options.
- That option remains ticked, meaning it is binding now and in the future whenever a bookmark gets added/renamed/removed.

**Cyberduck** on the other hand allows to sort by Nickname or Hostname or Protocol or Manual Sort Order (effectively!)
 - by going to: Main Menu → Bookmark → Sort By → Triggering 1 of the 3 options as a oneshot (no option has a tick thereafter!)
 - After the oneshot operation if you re-order bookmarks in the bookmark window by drag and drop, this effectively achieves a manual sorting order.
 - This was/is okay as long as only Cyberduck operates on the bookmarks.
 - But when Mountain Duck is accessing the centralized bookmarks too, their different behavior of "Sort By" seems to result in an unhandled situation or cross-effect, which results in a bug, where the bookmarks end up at an unexpected position or are lost altogether.

**Comment by porg** [comment] 2024-10-29 18:43
If this is confirmed to be the cause then my proposal would be this harmonization:
- Both "Cyberduck" and "Mountain Duck"
  - get a 4th explicit option "Manually Sorted"
  - the chosen option gets persisted by a tick (as opposed to a oneshot operation)
- If "Mountain Duck" has "✓ Manually Sorted" ticked then there's a 5th option "Manage Bookmarks…"
  - As long as "Mountain Duck" ha no such editor, it could simply be called "Manage bookmarks in Cyberduck …" which opens Cyberduck with a new window where one can manage the bookmarks.

Or if this is too much then minimal fix would be that in Cyberduck:
- You remove the implicit manual sorting option (remove drag-n-drop from the bookmark window)
- You manage to keep manual sorting order, while avoiding data loss in the interplay with Cyberduck.

**Comment by porg** [comment] 2024-11-03 13:26
@dkocher I now have a stable reproduction:

See the two screen recordings below: _fan noise in background, sorry annoying but spoken words are audible._

1) **Cyberduck** (4.16.3) alone: Combining oneshot operations `Menu → Bookmarks → Sort by` + manual re-ordering by drag'n'drop in all possible ways:
- ✅ Data loss never occurs.
- ❌ One usability issue remains: The drag-n-dropped item often lands not at the destination but dissappears and then reappears at the bottom of the list.

https://github.com/user-attachments/assets/8f60c586-7cfe-4a4f-824c-d81461c8b6ca


2) **Cyberduck and Mountain Duck both running**
- **Mountain Duck**: Set to certain sort order.
- **Cyberduck** (9.0.2): Given bookmark `A-J` currently sorted alphabetically.
  - At least once it worked a expected: Drag a **middle** item like `F` to the top (before `A`) → ✅ Works.
  - Data loss:
    - Drag the **second to last** item `I` to the top →  ❌ Bookmark is lost.
    - Drag the **last element** upwards by any amount (1, 2, or to the very top) →  ❌ Bookmark is lost.
  - Annoyance: Sometimes items do not land at the dropped position but disappear and then reappear at the bottom.
    - Drag the second to last item `H` above the current manual sorted top item `G`: ❗️ Disappears and then reappears at the bottom. Also a bug, but at least not data loss.

https://github.com/user-attachments/assets/fb3f5edc-430c-485f-84e0-7ed1b514d23b

**Comment by simonrob** [comment] 2024-11-03 20:45
Not one of the original reporters, but just confirming that I experience the same issue with a list currently containing 45 bookmarks. Mountain Duck is not present (and never has been).

**Closed** 2024-11-15 17:23 UTC
Labels: bug

**Comment by porg** [comment] 2024-11-16 08:47
Great! In which build will that fix be included? 

If you think it needs wide testing I offer to test it prior releasing if you provide me a nightly build. I still have my backed up bookmark set ready for testing.

**Comment by dkocher** [comment] 2024-11-16 12:10
> Great! In which build will that fix be included?
> 
> If you think it needs wide testing I offer to test it prior releasing if you provide me a nightly build. I still have my backed up bookmark set ready for testing.

The fix can be found in [snapshot build](https://docs.cyberduck.io/cyberduck/faq/#snapshot-and-beta-builds) _9.0.4.42328_.
