### ISSUE TITLE
Duplicate file stopped working with last update 

### ISSUE THREAD

**Issue by earmellin** [iterate-ch/cyberduck#14442] opened 2023-03-29 15:13 UTC
Hello, 

with the latest update the "duplicate file" stopped working, the window where you can enter the file name opens but clicking on Duplicate nothing happens 

version: 8.5.7
Macbook pro M2
Os Ventura 13.2.1

**Comment by dkocher** [comment] 2023-03-29 15:13
Duplicate of #14413.

**Closed by dkocher** 2023-03-29 15:13 UTC
