### ISSUE TITLE
Configuration with Storj DCS provider doesn't work

### ISSUE THREAD

**Issue by AlexeyALeonov** [iterate-ch/cyberduck#16672] opened 2024-12-14 00:35 UTC
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
If I configure Cyberduck with provider Storj DCS, it would offer a correct endpoint gateway.storjshare.io and I can specify an Access Key and Secret Access Key, but the opened bookmark will appear empty. If I change the provider to Amazon S3 and manually update the suggested endpoint of `s3.amazonaws.com` to the correct one `gateway.storjshare.io`, then the same Access Key and Access Secret Key is starting to work.

**To Reproduce**
1. Go to 'Open connection'
2. Click on provider list and select 'Storj DCS'
3. Fill **Access Key** with the Storj S3 Access Key
4. Fill **Secret Key** with the Storj S3 Secret Key
5. Click **Connect** button
6. The window appear empty

**Expected behavior**
The Storj DCS connection should show buckets and objects.

**Workaround**
7. Edit the bookmark for Storj DCS and select `Amazon S3` as a provider
8. Change the endpoint to `gateway.storjshare.io`
9. Now use this bookmark - the window will show buckets

**Screenshots**
![image](https://github.com/user-attachments/assets/73e878f0-a134-48db-8933-36ca1738f3cd)
![image](https://github.com/user-attachments/assets/99db4093-3d72-4d74-9a1b-dd352fa81a15)

After the change to *Amazon S3* and use the correct endpoint `gateway.storjshare.io`:
![image](https://github.com/user-attachments/assets/08947dee-ecde-4b68-8d33-01505b51b6f5)
![image](https://github.com/user-attachments/assets/511076ee-8c0d-48be-af0c-76648a0af0a2)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]: Windows 10, 10.0.19045 N/A Build 19045
 - Version [e.g. 22]: Cyberduck 9.1.0 (42520)

**Comment by dkocher** [comment] 2024-12-14 08:07
This may be a duplicate of #16659. Can you reproduce with the current [snapshot build](https://docs.cyberduck.io/cyberduck/preferences/#snapshot-builds)?

**Comment by AlexeyALeonov** [comment] 2024-12-15 01:27
yes, the snapshot version works

**Closed** 2024-12-15 10:12 UTC
Labels: s3
