### ISSUE TITLE
Recursive search displaying folders not containing files matching the pattern

### ISSUE THREAD

**Issue by tsvng** [iterate-ch/cyberduck#13925] opened 2022-12-02 00:26 UTC
**Describe the bug**
When using the recursive search feature to find files matching a certain pattern, it will display folders that DO NOT contain any files matching the pattern. When expanding these folders that do not contain files matching the pattern, it will not list any files (essentially act as an empty folder).

**To Reproduce**
1. Go to a folder containing several directories
2. Click on the search bar and enter a pattern that will hit a file within at least one, but not all of the child directories.
3. Hit 'return' on the keyboard to enact the recursive search.
4. See error where folders that do not contain any files matching the pattern will be listed.

**Expected behavior**
[Per Cyberduck Docs ](https://docs.cyberduck.io/cyberduck/browser/#filter-and-search)
Only files matching the search or folders with containing files matching the pattern will be displayed in the browser.

**Desktop (please complete the following information):**
 - OS: macOS Monterey v12.5.1
 - Cyberduck Version 8.5.1 (38745)

**Additional context**
Used to work as expected until I updated to the latest version.

**Comment by dkocher** [comment] 2022-12-02 09:46
Please let me know for what protocols you can reproduce this.

**Comment by tsvng** [comment] 2022-12-02 17:06
This is when using Amazon S3 protocol.

**Comment by porg** [comment] 2023-02-03 14:32
- Docs:
  > Only files matching the search or folders with containing files matching the pattern will be displayed in the browser.
  - 👍 Usability wise in an **recursive outline view** (a.k.a. "tree view") it makes sense to hide folders which have no matches in any of their deeper descendants. Those would be just an endless "orphan line" (folder, containing folder, containing folder, … containing folder which contains nothing that matched).
  - 👉 Whereas when **filtering in the current directory only** or in my proposed [sticky filtered browsing](https://github.com/iterate-ch/cyberduck/issues/14181) the descendants should not matter at all!
    - Filtering, whether inclusive or exclusive should only apply on the current level!
    - Real orphan directories show up, unless a [negative query operator](https://github.com/iterate-ch/cyberduck/issues/14180)) results them to get hidden.
    - And also directories, which would be empty if queried recursively, should be shown. Because the search is not recursive, but only applies to the active directory. Just wanted to mention that explicitly. That this is not changed into the wrong direction.

- Today I also proposed #14182
  - @tsvng : Would this more differentiated search option help your in this your use case or other use cases?
  - @dkocher  What do you say?
  - All: Feel free to tune in over there, if interested.

**Comment by dkocher** [comment] 2023-02-03 14:34
> * 👍 Usability wise in an **recursive outline view** (a.k.a. "tree view") it makes sense to hide folders which have no matches in any of their deeper descendants. Those would be just an endless "orphan line" (folder, containing folder, containing folder, … containing folder which contains nothing that matched).

Fixed with #14183.

**Comment by porg** [comment] 2023-02-03 17:45
1. Glad to read about the fix.

2. I'd appreciate a reaction to this my statement/inquiry:
>   * 👉 Whereas when **filtering in the current directory only** or in my proposed [sticky filtered browsing](https://github.com/iterate-ch/cyberduck/issues/14181) the descendants should not matter at all!
- For the proposed **sticky filtered browsing** this is just to keep in mind.
- For **filtering in the current directory only**: Is this working as described?

**Closed** 2023-02-06 07:28 UTC
Labels: bug, s3, googledrive, googlestorage, dropbox, dracoon
