### ISSUE TITLE
1.5 GB zip file does not stop downloading 

### ISSUE THREAD

**Issue by delook** [iterate-ch/cyberduck#14375] opened 2023-03-17 21:51 UTC
1.5 GB zip file does not finisch downloading, instead counting up to 4 GB and more. 
Version 8.5.6 (39394)
macOS 10.15.7

**Comment by dkocher** [comment] 2023-03-23 13:25
Possibly a duplicate of #14081.

**Closed** 2023-06-16 10:44 UTC
